building with x11-libs/wxGTK-2.8.12 on Gentoo
Original code would not build on my Gentoo workstation with
wxGTK-2.8.12 due to ambiguous casting errors such as:

g++ -Wall -Werror -MT obj/BossaWindow.o -MD -MP -MF obj/BossaWindow.d
-DVERSION=\"1.2.1\" -g -O2
-I/usr/lib64/wx/include/gtk2-unicode-release-2.8 -I/usr/include/wx-2.8
-D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXGTK__ -pthread -DWX_PRECOMP
-Wno-ctor-dtor-privacy -O2 -fno-strict-aliasing  -c -o obj/BossaWindow.o
src/BossaWindow.cpp
src/BossaWindow.cpp: In constructor 'BossaWindow::BossaWindow()':
src/BossaWindow.cpp:105:34: error: conversion from 'const char [5]' to
'const wxString' is ambiguous
/usr/include/wx-2.8/wx/string.h:692:3: note: candidates are:
wxString::wxString(wxChar, size_t) <near match>
/usr/include/wx-2.8/wx/string.h:682:3: note:
wxString::wxString(int) <near match>
src/BossaWindow.cpp:112:63: error: no matching function for call to
'LinuxPortFactory::create(const wxCharBuffer)'
src/LinuxPortFactory.h:50:29: note: candidate is: virtual
SerialPort::Ptr LinuxPortFactory::create(const std::string&)
src/BossaWindow.cpp:120:34: error: conversion from 'const char [5]' to
'const wxString' is ambiguous
/usr/include/wx-2.8/wx/string.h:692:3: note: candidates are:
wxString::wxString(wxChar, size_t) <near match>
/usr/include/wx-2.8/wx/string.h:682:3: note:
wxString::wxString(int) <near match>

Through careful placement of various casts and conversions BOSSA
was made to build against wxGTK-2.8.12 and all 3 executables now
run but have not been tested functionality against any devices.